name: Android
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 100
    runs-on: macos-12
#    env:
#      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install detox dependencies
      run: | 
        brew tap wix/brew
        brew install applesimutils
        npm install -g react-native-cli @react-native-community/cli
        npm install -g detox-cli
    - name: Install java
      run: |        
        brew tap homebrew/cask-versions
        brew install --cask zulu11
    - name: Java Setup
      uses: actions/setup-java@v3.9.0
      distribution: 11
    - name: Build with Gradle
      run: ./gradlew build
#    - name: Show simulator info
#      run: applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/'
#    - name: Run iOS simulator
#      run: open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID $(applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/')
#    - uses: JarvusInnovations/background-action@v1
#      name: Run iOS simulator
#      with:
#        wait-for: 1m
#        wait-on: xcrun simctl list devices booted | grep "iPhone 14"
#        run: open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID $(applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/')
#    - uses: futureware-tech/simulator-action@v2
#      name: Run Simulator
#      with:
#        model: 'iPhone 14'
    - name: Install dependencies
      run: yarn
#    - name: Configure JDK 1.11
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'temurin'
#        java-version: '11'
#    - name: Install Java JDK
#      uses: joschi/setup-jdk@v1
#      with:
#        java-version: 'openjdk8'
#        architecture: 'x64'
#      env:
#        # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
#        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Download Android Emulator Image
      run: |
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name emu --device "Nexus 5X" -k 'system-images;android-29;google_apis;x86'
        $ANDROID_HOME/emulator/emulator -list-avds
    - name: Start MongoDB
      uses: ankane/setup-mongodb@v1
      with:
        mongodb-version: '5.0'
    - name: Start Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6'
#    - run: export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
    - name: Build with detox
      run: detox build -c android.emu.release
    - name: Android Emulator
      timeout-minutes: 10
      continue-on-error: true
      run: |
        echo "Starting emulator"
        nohup $ANDROID_HOME/emulator/emulator -avd emu -no-audio -no-snapshot -no-window &
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
        $ANDROID_HOME/platform-tools/adb devices
        echo "Emulator started"
    - name: Background App Server
      uses: BerniWittmann/background-server-action@v1
      with:
        start: yarn start
        wait-on: "http://localhost:3000"
#    - name: Metro
#      uses: BerniWittmann/background-server-action@v1
#      with:
#        start: yarn metro
#        wait-on: "http://localhost:8081"
# emulator @Nexus_5X & until adb shell true; do sleep .5; done &&
    - name: Run tests with detox
      run: bash ${{ github.workspace }}/run-e2e-android-release.sh
