name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: brew tap wix/brew
    - run: brew install applesimutils
    #- run: npm install -g react-native-cli
    - run: npm install -g detox-cli
    - name: Install dependencies
      run: yarn
    - name: Start MongoDB
      uses: ankane/setup-mongodb@v1
      with:
        mongodb-version: '5.0'
    - name: Start Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6'
    - run: cd ./ios && pod install && cd ..
    - name: Background App Server
      uses: BerniWittmann/background-server-action@v1
      with:
        start: yarn start, yarn metro
        wait-on: "http://localhost:3000"
    - name: Build with detox
      run: detox build --configuration ios.sim.debug
    - name: Run tests with detox
      run: detox test --configuration ios.sim.debug
#      env:
#        CI: true
#        PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
