name: iOS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 100
    runs-on: macos-12
#    env:
#      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: npm install -g react-native-cli
    - run: npm install -g detox-cli
#    - name: Show simulator info
#      run: applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/'
#    - name: Run iOS simulator
#      run: open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID $(applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/')
#    - uses: JarvusInnovations/background-action@v1
#      name: Run iOS simulator
#      with:
#        wait-for: 1m
#        wait-on: xcrun simctl list devices booted | grep "iPhone 14"
#        run: open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID $(applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/')

#    - name: Configure JDK 1.11
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'temurin'
#        java-version: '11'
#
#    - uses: maxim-lobanov/setup-xcode@v1
#      with:
#        xcode-version: 'latest-stable'

#    # Set path variables needed for caches
#    - name: Set workflow variables
#      id: workflow-variables
#      run: |
#        echo "metro-cache=$HOME/.metro" >> $GITHUB_OUTPUT
#        echo "xcode-version=$(xcodebuild -version|tail -1|cut -f3 -d' ')" >> $GITHUB_OUTPUT
#        echo "yarn-cache-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
#    - uses: actions/cache@v3
#      name: Yarn Cache
#      id: yarn-cache
#      with:
#        path: ${{ steps.workflow-variables.outputs.yarn-cache-dir }}
#        key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
#        restore-keys: ${{ runner.os }}-yarn-v1
#
#    - uses: actions/cache@v3
#      name: Detox Framework Cache
#      id: detox-cache
#      with:
#        path: ~/Library/Detox/ios
#        key: ${{ runner.os }}-detox-framework-cache-${{ steps.workflow-variables.outputs.xcode-version }}
#
#    # Detox is compiled during yarn install, using Xcode, set up cache first
#    - uses: hendrikmuhs/ccache-action@v1.2
#      name: Xcode Compile Cache
#      with:
#        key: ${{ runner.os }}-v2 # makes a unique key w/related restore key internally
#        max-size: 1500M
#
#    - name: Install dependencies
#      run: yarn --no-audit --prefer-offline

#    - name: Install brew utilities
#      uses: nick-invision/retry@v2
#      with:
#        timeout_minutes: 5
#        retry_wait_seconds: 60
#        max_attempts: 3
#        command: HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew && HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils xcbeautify && applesimutils --list
    - run: cd ./ios && pod install && cd ..
    - name: Build
      run: yarn build
    - name: Start MongoDB
      uses: ankane/setup-mongodb@v1
      with:
        mongodb-version: '5.0'
    - name: Start Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6'
#    - run: react-native start
#    - name: Open iOS simulator
#      run: open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID $(applesimutils --byName "iPhone 14" --list | grep 'udid' | sed 's/.*:.*\"\(.*\)\",/\1/')
#    - uses: futureware-tech/simulator-action@v2
#      name: Run Simulator
#      with:
#        model: 'iPhone 14'
    - name: Build with detox
      run: detox build --configuration ios.sim.debug
    - name: Background App Server
      uses: BerniWittmann/background-server-action@v1
      with:
        start: yarn start-production
        wait-on: "http://localhost:3000"
    - name: Metro
      uses: BerniWittmann/background-server-action@v1
      with:
        start: yarn metro
        wait-on: "http://localhost:8081"
    - name: Run tests with detox
      run: detox test --configuration ios.sim.debug --cleanup --debug-synchronization 200
